version: "3"
services:
  nginx:
    image: jwilder/nginx-proxy:alpine
    restart: always
    networks:
      - frontend
    ports:
      - "443"
      - "5000"
    volumes:
      - ./volumes/ssl:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro

  teampass:
    image: fsarmanho/teampass:3
    restart: always
    environment:
      VIRTUAL_HOST: teampasscase.anac.gov.br
    networks:
      - frontend
      - backend
    volumes:
      - ./volumes/teampass/app:/var/www/html
      - ./volumes/teampass/conf:/usr/local/teampass/conf

  db:
    restart: always
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: teampass
      MYSQL_PASSWORD: teampass
      MYSQL_USER: teampass
    volumes:
      - ./volumes/db:/var/lib/mysql
    networks:
      - backend

networks:
  frontend:
  backend: